### PR TITLE
use latest alpine

### PR DESCRIPTION
**Pull request by grosser**
@aksgithub 

... can you try to make we admin in case I need to change sth else too :)
... if you no longer want the repo also feel free to transfer it to me

### CODE REVIEW

**Review by ankilosaurus — APPROVED** [review]

**Comment by ankilosaurus** [comment]
@grosser do you need new docker image based off this or wait for another change that you are making?

**Comment by grosser** [comment]
yes, new image plaese :)

**Comment by ankilosaurus** [comment]
v1.2.2

**Comment by grosser** [comment]
just checked ... we use our alpine and pick the executable from this docker image :)

**Pull request merged**
